### ISSUE TITLE
Auth Settings

### ISSUE THREAD

**Issue by alteredorange** [samuelgozi/firebase-storage-lite#4]
I was doing my testing with auth turned off, but curious how to use auth with file uploads (i.e. can only upload when logged in).  I have a logged in user, but I'm not sure what you mean by pass in the auth object. Any help would be appreciated, thanks!
Rules:

`rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}`

**Comment by samuelgozi** [comment]
If you use my [Auth library](https://github.com/samuelgozi/firebase-auth-lite) you can pass in an instance of it as the second argument to the `Reference` constructor:

```js
import Reference from 'firebase-storage-lite';
import Auth from 'firebase-auth-lite';
import config from 'firebaseConfig.js';

const auth = new Auth(config);
const bucket = new Reference(config.storageBucket, auth);
```
You only need to pass the `Auth` instance if you instantiate `Auth` with `new`.
```js
const auth = new Auth(config);
const bucket = new Reference(config.storageBucket, auth);

// Returns a new reference with the auth already set.
const avatar = bucket.child('user/avatar.png');

// All of the requests will be done with the user's credentials.
avatar.delete();
```

**Comment by alteredorange** [comment]
Awesome, thanks for the explanation!
